object FrImpressaoPrePedido: TFrImpressaoPrePedido
  Left = 0
  Top = 0
  Caption = 'FrImpressaoPrePedido'
  ClientHeight = 197
  ClientWidth = 381
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object ppDb: TppDBPipeline
    UserName = 'Db'
    Left = 24
    Top = 24
  end
  object ppRep: TppReport
    AutoStop = False
    DataPipeline = ppDb
    PrinterSetup.BinName = 'Default'
    PrinterSetup.DocumentName = 'Report'
    PrinterSetup.PaperName = 'A4'
    PrinterSetup.PrinterName = 'Default'
    PrinterSetup.SaveDeviceSettings = False
    PrinterSetup.mmMarginBottom = 6350
    PrinterSetup.mmMarginLeft = 6350
    PrinterSetup.mmMarginRight = 6350
    PrinterSetup.mmMarginTop = 6350
    PrinterSetup.mmPaperHeight = 297000
    PrinterSetup.mmPaperWidth = 210000
    PrinterSetup.PaperSize = 9
    ArchiveFileName = '($MyDocuments)\ReportArchive.raf'
    DeviceType = 'Screen'
    DefaultFileDeviceType = 'PDF'
    EmailSettings.ReportFormat = 'PDF'
    LanguageID = 'Default'
    OpenFile = False
    OutlineSettings.CreateNode = False
    OutlineSettings.CreatePageNodes = False
    OutlineSettings.Enabled = False
    OutlineSettings.Visible = False
    ThumbnailSettings.Enabled = True
    ThumbnailSettings.Visible = True
    ThumbnailSettings.DeadSpace = 30
    ThumbnailSettings.PageHighlight.Width = 3
    PDFSettings.EmbedFontOptions = [efUseSubset]
    PDFSettings.EncryptSettings.AllowCopy = True
    PDFSettings.EncryptSettings.AllowInteract = True
    PDFSettings.EncryptSettings.AllowModify = True
    PDFSettings.EncryptSettings.AllowPrint = True
    PDFSettings.EncryptSettings.AllowExtract = True
    PDFSettings.EncryptSettings.AllowAssemble = True
    PDFSettings.EncryptSettings.AllowQualityPrint = True
    PDFSettings.EncryptSettings.Enabled = False
    PDFSettings.EncryptSettings.KeyLength = kl40Bit
    PDFSettings.EncryptSettings.EncryptionType = etRC4
    PDFSettings.FontEncoding = feAnsi
    PDFSettings.ImageCompressionLevel = 25
    PDFSettings.PDFAFormat = pafNone
    PreviewFormSettings.PageBorder.mmPadding = 0
    PreviewFormSettings.PageDisplay = pdContinuous
    PreviewFormSettings.WindowState = wsMaximized
    PreviewFormSettings.ZoomSetting = zsPageWidth
    RTFSettings.DefaultFont.Charset = DEFAULT_CHARSET
    RTFSettings.DefaultFont.Color = clWindowText
    RTFSettings.DefaultFont.Height = -13
    RTFSettings.DefaultFont.Name = 'Arial'
    RTFSettings.DefaultFont.Style = []
    TextFileName = '($MyDocuments)\Report.pdf'
    TextSearchSettings.DefaultString = '<FindText>'
    TextSearchSettings.Enabled = True
    XLSSettings.AppName = 'ReportBuilder'
    XLSSettings.Author = 'ReportBuilder'
    XLSSettings.Subject = 'Report'
    XLSSettings.Title = 'Report'
    XLSSettings.WorksheetName = 'Report'
    Left = 104
    Top = 24
    Version = '19.0'
    mmColumnWidth = 0
    DataPipelineName = 'ppDb'
    object ppHeaderBand1: TppHeaderBand
      BeforePrint = ppHeaderBand1BeforePrint
      Background.Brush.Style = bsClear
      Border.BorderPositions = [bpBottom]
      Border.Visible = True
      Border.mmPadding = 0
      mmBottomOffset = 0
      mmHeight = 29633
      mmPrintPosition = 0
      object ppNomeEmpresa: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'NomeEmpresa'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 0
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 3969
        mmLeft = 0
        mmTop = 6096
        mmWidth = 197380
        BandType = 0
        LayerName = Foreground
      end
      object ppPrePedido: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'PrePedido'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 1
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 12
        Font.Style = [fsBold]
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 5027
        mmLeft = 0
        mmTop = 1058
        mmWidth = 197380
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel1: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label1'
        RTLReading = False
        Border.mmPadding = 0
        Caption = 'End.:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 3440
        mmLeft = 2204
        mmTop = 10848
        mmWidth = 6879
        BandType = 0
        LayerName = Foreground
      end
      object ppEnderecoEmpresa: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'EnderecoEmpresa'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 2
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 8995
        mmTop = 10848
        mmWidth = 119768
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel2: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label2'
        RTLReading = False
        Border.mmPadding = 0
        Caption = 'Tel.:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3440
        mmLeft = 129117
        mmTop = 10848
        mmWidth = 6085
        BandType = 0
        LayerName = Foreground
      end
      object ppTelefone: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'Telefone'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 3
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 135372
        mmTop = 10848
        mmWidth = 18515
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel3: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label3'
        RTLReading = False
        Border.mmPadding = 0
        Caption = 'CNPJ:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3440
        mmLeft = 154688
        mmTop = 10848
        mmWidth = 8996
        BandType = 0
        LayerName = Foreground
      end
      object ppCnpj: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'Cnpj'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 4
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 163149
        mmTop = 10848
        mmWidth = 31755
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel4: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label4'
        RTLReading = False
        Border.mmPadding = 0
        Caption = 'Emiss'#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3440
        mmLeft = 2117
        mmTop = 14819
        mmWidth = 12171
        BandType = 0
        LayerName = Foreground
      end
      object ppEmissao: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'Emissao'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 5
        DataType = dtDate
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 15610
        mmTop = 14819
        mmWidth = 16051
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel5: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label5'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        Caption = 'Vendedor:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3440
        mmLeft = 71619
        mmTop = 14819
        mmWidth = 14288
        BandType = 0
        LayerName = Foreground
      end
      object ppVendedorNome: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'VendedorNome'
        RTLReading = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 6
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 96044
        mmTop = 14819
        mmWidth = 18785
        BandType = 0
        LayerName = Foreground
      end
      object ppVendedorId: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'VendedorId'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 7
        DataType = dtInteger
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 86701
        mmTop = 14819
        mmWidth = 8467
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel6: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label6'
        RTLReading = False
        Border.mmPadding = 0
        Caption = 'Previs'#227'o:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3440
        mmLeft = 33602
        mmTop = 14820
        mmWidth = 12700
        BandType = 0
        LayerName = Foreground
      end
      object ppPrevisao: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'Previsao'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 8
        DataType = dtDate
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 47095
        mmTop = 14819
        mmWidth = 16050
        BandType = 0
        LayerName = Foreground
      end
      object ppLine1: TppLine
        DesignLayer = ppDesignLayer1
        UserName = 'Line1'
        Border.mmPadding = 0
        Weight = 0.750000000000000000
        mmHeight = 801
        mmLeft = 0
        mmTop = 18788
        mmWidth = 197380
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel7: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label7'
        RTLReading = False
        Border.mmPadding = 0
        Caption = 'Cliente:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3440
        mmLeft = 2204
        mmTop = 20200
        mmWidth = 10234
        BandType = 0
        LayerName = Foreground
      end
      object ppClienteId: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'ClienteId'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 9
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 13579
        mmTop = 20200
        mmWidth = 7232
        BandType = 0
        LayerName = Foreground
      end
      object ppClienteNome: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'ClienteNome'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 10
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 21253
        mmTop = 20200
        mmWidth = 92608
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel8: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label8'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        Caption = 'CPF/CNPJ:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3439
        mmLeft = 114127
        mmTop = 20200
        mmWidth = 15610
        BandType = 0
        LayerName = Foreground
      end
      object ppClienteCpfCnpj: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'ClienteCpfCnpj'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 11
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 129911
        mmTop = 20200
        mmWidth = 26811
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel9: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label9'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        Caption = 'RG/IE:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3439
        mmLeft = 157692
        mmTop = 20286
        mmWidth = 8202
        BandType = 0
        LayerName = Foreground
      end
      object ppClienteRgIe: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'ClienteRgIe'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 12
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 166688
        mmTop = 20200
        mmWidth = 28222
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel10: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label10'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        Caption = 'End.:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3439
        mmLeft = 2118
        mmTop = 24260
        mmWidth = 6350
        BandType = 0
        LayerName = Foreground
      end
      object ppClienteEndereco: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'ClienteEndereco'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 13
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 9434
        mmTop = 24342
        mmWidth = 120297
        BandType = 0
        LayerName = Foreground
      end
      object ppLabel11: TppLabel
        DesignLayer = ppDesignLayer1
        UserName = 'Label11'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        Caption = 'Tel.:'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = [fsBold]
        FormFieldSettings.FormSubmitInfo.SubmitMethod = fstPost
        FormFieldSettings.FormFieldType = fftNone
        Transparent = True
        mmHeight = 3439
        mmLeft = 129911
        mmTop = 24342
        mmWidth = 6085
        BandType = 0
        LayerName = Foreground
      end
      object ppClienteTelefone: TppVariable
        DesignLayer = ppDesignLayer1
        UserName = 'ClienteTelefone'
        RTLReading = False
        AutoSize = False
        Border.mmPadding = 0
        BlankWhenZero = False
        CalcOrder = 14
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clBlack
        Font.Name = 'Times New Roman'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3439
        mmLeft = 136880
        mmTop = 24342
        mmWidth = 18514
        BandType = 0
        LayerName = Foreground
      end
      object ppLine2: TppLine
        DesignLayer = ppDesignLayer1
        UserName = 'Line2'
        Border.mmPadding = 0
        Weight = 0.750000000000000000
        mmHeight = 801
        mmLeft = 0
        mmTop = 28465
        mmWidth = 197380
        BandType = 0
        LayerName = Foreground
      end
    end
    object ppDetailBand1: TppDetailBand
      Background1.Brush.Style = bsClear
      Background2.Brush.Style = bsClear
      Border.mmPadding = 0
      mmBottomOffset = 0
      mmHeight = 0
      mmPrintPosition = 0
    end
    object ppSummaryBand1: TppSummaryBand
      Background.Brush.Style = bsClear
      Border.mmPadding = 0
      mmBottomOffset = 0
      mmHeight = 0
      mmPrintPosition = 0
    end
    object ppDesignLayers1: TppDesignLayers
      object ppDesignLayer1: TppDesignLayer
        UserName = 'Foreground'
        LayerType = ltBanded
        Index = 0
      end
    end
    object ppParameterList1: TppParameterList
    end
  end
end
