program OrdemServico;

uses
  Vcl.Forms,
  Main in 'View\Main.pas' {FrMain},
  Login in 'View\Login.pas' {FrLogin},
  mscorlib_TLB in 'Repository\mscorlib_TLB.pas',
  MaisVSLib_TLB in 'Repository\MaisVSLib_TLB.pas',
  DataBase in 'Repository\DataBase.pas',
  Funcoes_Alias in 'Repository\Funcoes_Alias.pas',
  DataSetFactory in 'Repository\DataSetFactory.pas',
  ConexaoBanco in 'Repository\ConexaoBanco.pas',
  Usuario in 'Entity\Usuario.pas',
  BoundObject in 'Core\BoundObject.pas',
  CryptDecrypt in 'Core\CryptDecrypt.pas',
  EnumConexao in 'Entity\Enum\EnumConexao.pas',
  UsuarioRepository in 'Repository\BaseDados\UsuarioRepository.pas',
  CadOrdemServico in 'View\CadOrdemServico.pas' {FrCadOrdemServico},
  FuncoesGerais in 'Core\FuncoesGerais.pas',
  OrdemServicoRepository in 'Repository\Empresa\OrdemServicoRepository.pas',
  OrdemServicoEntity in 'Entity\OrdemServicoEntity.pas',
  Pessoa in 'Entity\Pessoa.pas',
  PessoaRepository in 'Repository\Empresa\PessoaRepository.pas',
  EnumPessoaTipo in 'Entity\Enum\EnumPessoaTipo.pas',
  Mascara in 'Core\Mascara.pas',
  Consulta_Padrao in 'View\FormBasic\Consulta_Padrao.pas' {FrConsulta_Padrao},
  Consulta_Pessoa in 'View\Consulta_Pessoa.pas' {FrConsulta_Pessoa},
  PessoaService in 'Services\PessoaService.pas',
  Produto in 'Entity\Produto.pas',
  ProdutoRepository in 'Repository\Empresa\ProdutoRepository.pas',
  CustomMessage in 'Core\CustomMessage.pas',
  ProdutoService in 'Services\ProdutoService.pas',
  Consulta_Produto in 'View\Consulta_Produto.pas' {FrConsulta_Produto},
  EnumSituacaoOrdemServico in 'Entity\Enum\EnumSituacaoOrdemServico.pas',
  PermissaoUsuario in 'View\PermissaoUsuario.pas' {FrPermissaoUsuario},
  UsuarioService in 'Services\UsuarioService.pas',
  Log in 'Core\Log.pas',
  CustomExcept in 'Core\CustomExcept.pas',
  EstoqueRepository in 'Repository\Empresa\EstoqueRepository.pas',
  Excel in 'Core\Excel.pas',
  Parametros in 'Repository\BaseDados\Parametros.pas',
  EscolheCampos_Padrao in 'View\FormBasic\EscolheCampos_Padrao.pas' {FrEscolheCampos_Padrao},
  WindowsRecord in 'Core\WindowsRecord.pas',
  EscolheCampos_OrdemServico in 'View\EscolheCampos_OrdemServico.pas' {FrEscolheCampos_OrdemServico},
  cxGridExtentions in 'Core\cxGridExtentions.pas',
  Empresa in 'Entity\Empresa.pas',
  EmpresaRepository in 'Repository\BaseDados\EmpresaRepository.pas',
  EmpresaService in 'Services\EmpresaService.pas',
  OrdemServicoService in 'Services\OrdemServicoService.pas',
  AutorizacaoEstoque in 'View\AutorizacaoEstoque.pas' {FrAutorizacaoEstoque},
  SetorRepository in 'Repository\Empresa\SetorRepository.pas',
  Setor in 'Entity\Setor.pas',
  SetorService in 'Services\SetorService.pas',
  Consulta_Setor in 'View\Consulta_Setor.pas' {FrConsulta_Setor},
  FormaPagamento in 'Entity\FormaPagamento.pas',
  PlanoPagamento in 'Entity\PlanoPagamento.pas',
  FormaPagamentoRepository in 'Repository\Empresa\FormaPagamentoRepository.pas',
  PlanoPagamentoRepository in 'Repository\Empresa\PlanoPagamentoRepository.pas',
  FormaPagamentoService in 'Services\FormaPagamentoService.pas',
  PlanoPagamentoService in 'Services\PlanoPagamentoService.pas',
  Consulta_FormaPagamento in 'View\Consulta_FormaPagamento.pas' {FrConsulta_FormaPagamento},
  Consulta_PlanoPagamento in 'View\Consulta_PlanoPagamento.pas' {FrConsulta_PlanoPagamento},
  CtReceberRepository in 'Repository\Empresa\CtReceberRepository.pas',
  CtReceberService in 'Services\CtReceberService.pas',
  CtReceber in 'Entity\CtReceber.pas',
  InformacoesCartao in 'View\InformacoesCartao.pas' {FrInfCartao},
  Funcoes_EstoqueCST in 'Repository\Funcoes_EstoqueCST.pas',
  ParametrosOS in 'View\ParametrosOS.pas' {FrParametrosOS},
  FechamentoOS in 'View\FechamentoOS.pas' {FrFechamentoOS},
  CadastroCliente in 'View\CadastroCliente.pas' {FrCadastroCliente},
  Relatorios in 'View\Relatorios.pas' {FrRelatorios},
  RelComissoes in 'View\RelComissoes.pas' {FrRelComissoes},
  BairroService in 'Services\BairroService.pas',
  Bairro in 'Entity\Bairro.pas',
  BairroRepository in 'Repository\Empresa\BairroRepository.pas',
  Consulta_Bairro in 'View\Consulta_Bairro.pas' {FrConsulta_Bairro},
  CidadeRepository in 'Repository\Empresa\CidadeRepository.pas',
  Consulta_Cidade in 'View\Consulta_Cidade.pas' {FrConsulta_Cidade},
  Cidade in 'Entity\Cidade.pas',
  CidadeService in 'Services\CidadeService.pas',
  ConsultaCepRepository in 'Repository\Empresa\ConsultaCepRepository.pas',
  ConsultaCep in 'Entity\ConsultaCep.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TFrMain, FrMain);
  Application.CreateForm(TFrRelatorios, FrRelatorios);
  Application.CreateForm(TFrRelComissoes, FrRelComissoes);
  Application.CreateForm(TFrConsulta_Bairro, FrConsulta_Bairro);
  Application.CreateForm(TFrConsulta_Cidade, FrConsulta_Cidade);
  Application.Run;
end.
